### ISSUE TITLE
Undo doesn't update block states

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/Scarpet-edit#50]
This probably extends to other (or all) setting functions, since the cause of the bug is [this line](https://github.com/Ghoulboy78/World-edit-scarpet/blob/76e6e23cbf2b93a8cbcf920c8e1ba051ea31310e/world-edit.sc#L1316), where it checks if the new block batches the old one, in which case it doesn't set, but it doesn't check for different block states.

I noticed this when removing lava and then undoing the action, which left flowing lava, because `undo` didn't replace flowing lava with lava sources (both are lava blocks). I haven't done further testing, but it likely affects the whole app.

**Comment by Ghoulboy78** [comment]
then just need to add check for states no?

**Comment by Firigion** [comment]
Yes. Either that or remove the check altogether, idk which would be better.

**Comment by Ghoulboy78** [comment]
imo we should add check

**Comment by Firigion** [comment]
In that case, the check should also be for matching NBT, which would be really expensive. 

We either ditch the check completely or so something like only checking if the blocks and their properties are the same when the block type doesn't allow for NBT or block data. That way we can still do a reasonable check for most blocks, but also don't make the game grind to a halt when replacing chests with items in them with chests without items.

I still favour the no check approach, tho.
