### ISSUE TITLE
Some shapes are broken after merge of #49

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/Scarpet-edit#62]
- [ ] Cylinder, Cone and Pyramid with special orientations don't work at all (they don't place blocks)
- [ ] Cone creates pyramids, and pyramids have uneven slopes (here you can see 3 blocks at the bottom and the steps of one, instead of the expected two steps of two):
<img src="https://user-images.githubusercontent.com/64820010/111885006-f0f20700-89a3-11eb-9ec4-98c45645dd9e.png" width="50%" height="50%">

- [ ] Hollow ellipsoid has holes:
<img src="https://user-images.githubusercontent.com/64820010/111884424-59d78000-89a0-11eb-8a42-e23748faa626.png" width="50%" height="50%">

- [x] Hollow cuboid has strange shape:
<img src="https://user-images.githubusercontent.com/64820010/111884463-94d9b380-89a0-11eb-92a7-48e08a17339f.png" width="50%" height="50%">

- [ ] Hollow cube is very broken:
<img src="https://user-images.githubusercontent.com/64820010/111884494-b9ce2680-89a0-11eb-99dd-da144083aa08.png" width="50%" height="50%">

- [ ] Shpere is not isotropic (symmetrical):
<img src="https://user-images.githubusercontent.com/64820010/111884737-40373800-89a2-11eb-98a4-7edb8c05b760.png" width="50%" height="50%">

Don't fix what ain't broke, and if you do, make sure the fix works...

**Comment by Ghoulboy78** [comment]
I think most of these can be fixed when I rewrite them after gnembon/fabric-carpet#742 is accepted.

**Comment by Ghoulboy78** [comment]
except for ellipsoid, which is borked differently, but I think I can fix that aswell
