### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by altrisi** [Ghoulboy78/Scarpet-edit#83]
It's been a while since release, and there have been a lot of commits since that (https://github.com/Ghoulboy78/Scarpet-edit/compare/v1.2.0...master) (over 70).

What are we missing for a release? Is there anything currently failing horribly that must get fixed before releasing? Any feature that would be preferred to have in the next release?

This is mostly because I'm trying to make a ~horrible hack~ _way_ to put a scarpet edit "installer" on the app store, but I need the latest release to have the new app file name (`se.sc`) so the link doesn't change next one.

Feel free to edit the comment after this with the requirements.

**Comment by Ghoulboy78** [comment]
Ok I moved all the issues marked as for v1.3 to v1.4, so I can update rn.

**Comment by altrisi** [comment]
Do you think languages should also be added in the release?

Since language files may change in dev.

**Comment by Ghoulboy78** [comment]
ok, ye tru... but whatevs.
